### ISSUE TITLE
About results on NewsRoom

### ISSUE THREAD

**Issue by xipq** [jinlanfu/GPTScore#4]
Hi, thanks for your brilliant and comprehensive work.

I am recently working on using GPTscore to evaluate the NewsRoom benchmark. I found that there are three different annotations for each sample in the [Dataset](https://github.com/lil-lab/newsroom/tree/master/humaneval), which are not very cosistent inherently. If i take all of them for correlation analysis, the results are far below reported. 

I would like to know that, how you processed the NewsRoom dataset for correlation analysis (eg. averaging the 3 annotations? or else). Thanks and looking forward for your response.

**Comment by jinlanfu** [comment]
Yes, we calculate the human score for each sample by averaging the scores from multiple annotators. What's more,  for the datasets utilized in our work,  if multiple annotation scores are available for one example, we take the average score as the final human score.

**Comment by xipq** [comment]
Thanks for your helpful reply and your work~
