### ISSUE TITLE
Multilingual Evaluation

### ISSUE THREAD

**Issue by mshen2** [jinlanfu/GPTScore#5]
Hi, really appreciate the nice work here! I understand that GPTScore is mainly designed for english text evaluation, I am just wondering, do you think it makes sense to use GPTScore for other languages evaluation, at least for high resource languages such as French and Chinese? Thanks!

**Comment by jinlanfu** [comment]
Hi, thanks for your interest in our paper!

If you choose GPT3 as the backbone, GPTScore supports multiple languages. When applying GPTScore to other languages, please consider the following:
(1) GPTScore supports various backbones, including OPT, GPT2, T5-FLAN, and GPT3. However, OPT, GPT2, and T5-FLAN do not inherently support multiple languages. To overcome this limitation, you can utilize multilingual models such as mT5 instead.
(2) The samples used for demonstration purposes are in English. When testing GPTScore in other languages, such as Chinese, it is advisable to replace the demonstration samples with samples in the target language (e.g., Chinese). This substitution may result in improved performance.

**Comment by mshen2** [comment]
Thanks for the explanation, these are very useful suggestions!
